### ISSUE TITLE
could not connect to server: Connection refused

### ISSUE THREAD

**Issue by G0dwin** [ohbarye/rails-react-typescript-docker-example#53]
I'm getting the following error when executing `docker-compose run backend rake db:create`:

```bash
Starting rails-react-typescript-docker-example_db_1 ... done
could not connect to server: Connection refused
        Is the server running on host "db" (198.105.244.23) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "db" (198.105.254.23) and accepting
        TCP/IP connections on port 5432?
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "host"=>"db", "username"=>"postgres", "password"=>nil, "pool"=>5, "database"=>"myapp_development"}
rake aborted!
PG::ConnectionBad: could not connect to server: Connection refused
        Is the server running on host "db" (198.105.244.23) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "db" (198.105.254.23) and accepting
        TCP/IP connections on port 5432?
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `initialize'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `new'
/usr/local/bundle/gems/pg-1.1.3/lib/pg.rb:56:in `connect'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:684:in `connect'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `initialize'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `new'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:40:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:809:in `new_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:853:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:832:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:793:in `acquire_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1008:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/connection_handling.rb:90:in `connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:12:in `connection'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/postgresql_database_tasks.rb:21:in `create'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:119:in `create'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:139:in `block in create_current'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:316:in `block in each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:313:in `each_current_configuration'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:138:in `create_current'
/usr/local/bundle/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:29:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

I'm running this on Windows 10, in powershell. I ran the commands listed in [the "Usage" section](../#usage) without ay modifications except upgrading to Ruby 2.5.3 in the `Gemfile` because executing `docker-compose run frontend yarn` caused an error due to a mismatch in Ruby versions.

Any help resolving this issue is appreciated, I going to continue to investigate myself and I'll update here if I find a resolution.

**Comment by G0dwin** [comment]
I was able to finally get the database created and get the server up and running by changing the volume in the db from `./tmp/db:/var/lib/postgresql/data` to `/var/lib/postgresql/data`. My guess is that this is a permissions issue, probably one that windows has a difficult time passing off from the windows user to postgres in linux.

Having the db mapped to an external directory is likely something that will prove convenient if I want to use pgAdmin to view the data but for now I can use the command line. There is likely a way to get this done, either by explicitly setting permissions in windows, or by creating the data directory as part of the setup by the postgres user. If I figure that out sometime I'll update again.
